version: '3.8'


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    command: bash -c "python -m alembic.config upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080"
    depends_on:
      postgres:
        condition: service_started


  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - "POSTGRES_HOST=${DB_HOST}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata:

